# Application config file.

[development]
DBICC = "SIT62"
DBATB2 = "QED"
DBPED = "QED"
queueurl = "amqp://admin:admin@172.19.218.104:5672/"
queuename = "tvs_collection"
updateorderurl = "http://localhost:8000/updateorder"


[production]
DBICC = "SIT62"
DBATB2 = "QED"
DBPED = "QED"
queueurl = "amqp://admin:admin@172.19.218.104:5672/"
queuename = "tvs_collection"
updateorderurl = "http://localhost:8000/updateorder"